import assert from 'node:assert/strict'
import { randomBytes } from 'node:crypto'
import test from 'node:test'

const testUri = process.env.TEST_MONGODB_URI; const testDatabase = process.env.TEST_MONGODB_DB_NAME
test('paid-hire comment authorization', { skip: !(testUri && testDatabase?.endsWith('_test')) && 'Set isolated Atlas test variables.' }, async (context) => {
  process.env.NODE_ENV = 'test'; process.env.MONGODB_URI = testUri; process.env.MONGODB_DB_NAME = testDatabase; process.env.JWT_SECRET = randomBytes(48).toString('hex'); process.env.CLIENT_ORIGINS = 'http://localhost:5173'
  const [{ default: request }, mongoose, { default: app }, { User }, { LawyerProfile }, { HiringRequest }, { Comment }, { createSessionToken }] = await Promise.all([import('supertest'), import('mongoose'), import('../src/app.js'), import('../src/models/User.js'), import('../src/models/LawyerProfile.js'), import('../src/models/HiringRequest.js'), import('../src/models/Comment.js'), import('../src/utils/auth.js')])
  await mongoose.connect(testUri, { dbName: testDatabase }); const tag = `comment-${randomBytes(5).toString('hex')}`; const emails = [`${tag}-u@x.test`, `${tag}-o@x.test`, `${tag}-l@x.test`]
  context.after(async () => { const users = await User.find({ email: { $in: emails } }); await Comment.deleteMany({ authorId: { $in: users } }); await HiringRequest.deleteMany({ clientId: { $in: users } }); await LawyerProfile.deleteMany({ userId: { $in: users } }); await User.deleteMany({ email: { $in: emails } }); await mongoose.disconnect() })
  const [user, other, lawyer] = await User.create([{ fullName: 'Paid Client', email: emails[0], role: 'user' }, { fullName: 'Other Client', email: emails[1], role: 'user' }, { fullName: 'Lawyer', email: emails[2], role: 'lawyer' }]); const profile = await LawyerProfile.create({ userId: lawyer.id, professionalPhotoUrl: 'https://i.ibb.co/x/a.png', specialization: 'Family Law', bio: 'Bio', consultationFeeMinor: 10000, experienceYears: 1, licenseNumber: 'L1', verificationStatus: 'paid', publicationStatus: 'published' }); await HiringRequest.create({ clientId: user.id, lawyerId: lawyer.id, lawyerProfileId: profile.id, specializationSnapshot: 'Family Law', feeMinorSnapshot: 10000, currency: 'USD', status: 'accepted', paymentStatus: 'paid' })
  const origin = 'http://localhost:5173'; const cookie = (person) => `legalease_session=${createSessionToken(person)}`; const post = (person, content = 'Clear and helpful service.') => request(app).post(`/api/lawyers/${profile.id}/comments`).set('Origin', origin).set('Cookie', cookie(person)).send({ content })
  assert.equal((await post(other)).status, 403); const made = await post(user); assert.equal(made.status, 201); assert.equal((await post(user)).status, 409); assert.equal((await request(app).get(`/api/lawyers/${profile.id}/comments`)).body.data.items.length, 1); assert.equal((await request(app).patch(`/api/comments/${made.body.data.comment.id}`).set('Origin', origin).set('Cookie', cookie(other)).send({ content: 'Nope' })).status, 404); assert.equal((await request(app).patch(`/api/comments/${made.body.data.comment.id}`).set('Origin', origin).set('Cookie', cookie(user)).send({ content: 'Updated helpful service.' })).status, 200); assert.equal((await request(app).delete(`/api/comments/${made.body.data.comment.id}`).set('Origin', origin).set('Cookie', cookie(user))).status, 204)
})
