import mongoose from 'mongoose'
import { User } from '../models/User.js'
import { LawyerProfile } from '../models/LawyerProfile.js'
import { HiringRequest } from '../models/HiringRequest.js'
import { PaymentTransaction } from '../models/PaymentTransaction.js'
import { isProfileComplete } from '../services/paymentService.js'
const fail = (m, s, c) => Object.assign(new Error(m), { statusCode: s, code: c })
const valid = (id) => mongoose.isObjectIdOrHexString(id)
const safeUser = (u) => ({ id: String(u._id), fullName: u.fullName, email: u.email, profileImageUrl: u.profileImageUrl || '', role: u.role, status: u.status, providers: u.providers, createdAt: u.createdAt })
export async function listUsers(req, res, next) { try { const q = req.validatedQuery; const f = {}; if (q.role) f.role = q.role; if (q.status) f.status = q.status; if (q.search) { const x = q.search.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); f.$or = [{ fullName: new RegExp(x, 'i') }, { email: new RegExp(x, 'i') }] }; const [items, totalItems] = await Promise.all([User.find(f).select('fullName email profileImageUrl role status providers createdAt').sort({ createdAt: -1, _id: -1 }).skip((q.page - 1) * 10).limit(10), User.countDocuments(f)]); res.json({ success: true, data: { items: items.map(safeUser) }, meta: { page: q.page, pageSize: 10, totalItems, totalPages: Math.ceil(totalItems / 10) } }) } catch (e) { next(e) } }
async function targetUser(id) { if (!valid(id)) throw fail('User was not found.', 404, 'USER_NOT_FOUND'); const u = await User.findById(id); if (!u) throw fail('User was not found.', 404, 'USER_NOT_FOUND'); return u }
async function protectLastAdmin(user, changes) { if (user.role !== 'admin' || user.status !== 'active' || (changes.role === 'admin' && changes.status !== 'deactivated') || (changes.status === 'active' && changes.role !== 'user' && changes.role !== 'lawyer')) return; if (await User.countDocuments({ role: 'admin', status: 'active' }) <= 1) throw fail('The final active admin cannot be changed.', 409, 'FINAL_ADMIN_PROTECTED') }
export async function updateRole(req, res, next) { try { const user = await targetUser(req.params.id); await protectLastAdmin(user, { role: req.body.role }); if (user.role === 'lawyer' && req.body.role !== 'lawyer') await LawyerProfile.updateOne({ userId: user._id, publicationStatus: 'published' }, { $set: { publicationStatus: 'unpublished' } }); user.role = req.body.role; await user.save(); res.json({ success: true, data: { user: safeUser(user) } }) } catch (e) { next(e) } }
export async function updateStatus(req, res, next) { try { const user = await targetUser(req.params.id); await protectLastAdmin(user, { status: req.body.status }); user.status = req.body.status; await user.save(); res.json({ success: true, data: { user: safeUser(user) } }) } catch (e) { next(e) } }
export async function listLawyers(req, res, next) { try { const q=req.validatedQuery; const filter={}; if(q.publicationStatus)filter.publicationStatus=q.publicationStatus; if(q.verificationStatus)filter.verificationStatus=q.verificationStatus; const [items,totalItems]=await Promise.all([LawyerProfile.find(filter).populate('userId','fullName email status role').sort({createdAt:-1,_id:-1}).skip((q.page-1)*10).limit(10),LawyerProfile.countDocuments(filter)]); res.json({ success: true, data: { items: items.map((p) => ({ id: String(p._id), fullName: p.userId?.fullName || 'Unavailable', email: p.userId?.email || '', accountStatus: p.userId?.status || 'deactivated', professionalPhotoUrl: p.professionalPhotoUrl, specialization: p.specialization, consultationFeeMinor: p.consultationFeeMinor, availability: p.availability, verificationStatus: p.verificationStatus, publicationStatus: p.publicationStatus, paidHireCount: p.paidHireCount, createdAt: p.createdAt })) },meta:{page:q.page,pageSize:10,totalItems,totalPages:Math.ceil(totalItems/10)} }) } catch (e) { next(e) } }
export async function moderateLawyer(req, res, next) { try { if (!valid(req.params.id)) throw fail('Lawyer profile was not found.', 404, 'LAWYER_PROFILE_NOT_FOUND'); const p = await LawyerProfile.findById(req.params.id).populate('userId', 'role status'); if (!p?.userId) throw fail('Lawyer profile was not found.', 404, 'LAWYER_PROFILE_NOT_FOUND'); const { action } = req.body; if (action === 'restore') { if (p.publicationStatus !== 'deleted') throw fail('Only deleted profiles can be restored.', 409, 'INVALID_PUBLICATION_TRANSITION'); p.publicationStatus = p.verificationStatus === 'paid' && isProfileComplete(p) ? 'unpublished' : 'draft'; p.deletedAt = null; p.deletedByRole = null } else { if (p.publicationStatus === 'deleted') throw fail('Restore this deleted profile before changing its publication state.', 409, 'PROFILE_DELETED'); if (action === 'publish') { if (p.userId.role !== 'lawyer' || p.userId.status !== 'active' || p.verificationStatus !== 'paid' || !isProfileComplete(p)) throw fail('This profile is not eligible for publishing.', 409, 'PROFILE_NOT_ELIGIBLE'); p.publicationStatus = 'published' } else if (action === 'unpublish') p.publicationStatus = 'unpublished'; else if (action === 'suspend') p.publicationStatus = 'suspended' } await p.save(); res.json({ success: true, data: { publicationStatus: p.publicationStatus } }) } catch (e) { next(e) } }
export async function deleteLawyer(req, res, next) { try { if (!valid(req.params.id)) throw fail('Lawyer profile was not found.', 404, 'LAWYER_PROFILE_NOT_FOUND'); const p = await LawyerProfile.findById(req.params.id); if (!p) throw fail('Lawyer profile was not found.', 404, 'LAWYER_PROFILE_NOT_FOUND'); p.publicationStatus = 'deleted'; p.deletedAt = new Date(); p.deletedByRole = 'admin'; await p.save(); res.status(204).end() } catch (e) { next(e) } }
export async function listTransactions(req, res, next) { try { const q=req.validatedQuery; const filter={}; if(q.type)filter.type=q.type; if(q.status)filter.status=q.status; const [items,totalItems]=await Promise.all([PaymentTransaction.find(filter).populate('payerId','fullName email').populate('lawyerId','fullName email').sort({createdAt:-1,_id:-1}).skip((q.page-1)*10).limit(10),PaymentTransaction.countDocuments(filter)]); res.json({ success: true, data: { items: items.map((t) => ({ id: String(t._id), type: t.type, payer: t.payerId ? { fullName: t.payerId.fullName, email: t.payerId.email } : null, lawyer: t.lawyerId ? { fullName: t.lawyerId.fullName, email: t.lawyerId.email } : null, amountMinor: t.amountMinor, currency: t.currency, status: t.status, createdAt: t.createdAt, paidAt: t.paidAt })) },meta:{page:q.page,pageSize:10,totalItems,totalPages:Math.ceil(totalItems/10)} }) } catch (e) { next(e) } }
export async function analytics(_req, res, next) { try { const [users, lawyers, paidHires, revenue, paidTransactions, monthlyRevenue, monthlyHires] = await Promise.all([User.countDocuments({ role: 'user' }), User.countDocuments({ role: 'lawyer' }), HiringRequest.countDocuments({ paymentStatus: 'paid' }), PaymentTransaction.aggregate([{ $match: { status: 'paid' } }, { $group: { _id: null, amountMinor: { $sum: '$amountMinor' } } }]), PaymentTransaction.countDocuments({ status: 'paid' }), PaymentTransaction.aggregate([{ $match: { status: 'paid', paidAt: { $ne: null } } }, { $group: { _id: { $dateToString: { format: '%Y-%m', date: '$paidAt' } }, revenueMinor: { $sum: '$amountMinor' } } }, { $sort: { _id: 1 } }]), HiringRequest.aggregate([{ $match: { paymentStatus: 'paid', paidAt: { $ne: null } } }, { $group: { _id: { $dateToString: { format: '%Y-%m', date: '$paidAt' } }, paidHires: { $sum: 1 } } }, { $sort: { _id: 1 } }])]); res.json({ success: true, data: { users, lawyers, paidHires, revenueMinor: revenue[0]?.amountMinor || 0, paidTransactions, monthlyRevenue: monthlyRevenue.map((x) => ({ month: x._id, revenueMinor: x.revenueMinor })), monthlyHires: monthlyHires.map((x) => ({ month: x._id, paidHires: x.paidHires })) } }) } catch (e) { next(e) } }
