import mongoose from 'mongoose'
import { env } from '../config/env.js'
import { LawyerProfile } from '../models/LawyerProfile.js'
import { PaymentTransaction } from '../models/PaymentTransaction.js'
import { createHiringCheckout, createVerificationCheckout, fulfillHiringSession, fulfillVerificationSession, isProfileComplete, reconcilePendingPayment, resetExpiredCheckout } from '../services/paymentService.js'

function fail(message, statusCode, code) { return Object.assign(new Error(message), { statusCode, code }) }
export async function startVerificationCheckout(request, response, next) { try { const { transaction, checkoutUrl } = await createVerificationCheckout(request.auth.user); return response.status(201).json({ success: true, data: { transactionId: transaction.id, checkoutUrl } }) } catch (error) { return next(error) } }
export async function startHiringCheckout(request, response, next) { try { const { transaction, checkoutUrl } = await createHiringCheckout(request.auth.user, request.params.requestId); return response.status(201).json({ success: true, data: { transactionId: transaction.id, checkoutUrl } }) } catch (error) { return next(error) } }
export async function getPaymentStatus(request, response, next) { try { if (!mongoose.isObjectIdOrHexString(request.params.id)) throw fail('Payment was not found.', 404, 'PAYMENT_NOT_FOUND'); let transaction = await PaymentTransaction.findOne({ _id: request.params.id, payerId: request.auth.user.id }); if (!transaction) throw fail('Payment was not found.', 404, 'PAYMENT_NOT_FOUND'); transaction = await reconcilePendingPayment(transaction); const profile = await LawyerProfile.findById(transaction.lawyerProfileId); if (!profile) throw fail('Payment was not found.', 404, 'PAYMENT_NOT_FOUND'); const hiringRequest = transaction.type === 'hiring_fee' ? await HiringRequest.findById(transaction.hiringRequestId).select('status paymentStatus paidAt') : null; if (transaction.type === 'hiring_fee' && !hiringRequest) throw fail('Payment was not found.', 404, 'PAYMENT_NOT_FOUND'); return response.json({ success: true, data: { transactionId: transaction.id, type: transaction.type, transactionStatus: transaction.status, paidAt: transaction.paidAt, verificationStatus: transaction.type === 'lawyer_verification' ? profile.verificationStatus : undefined, publicationStatus: transaction.type === 'lawyer_verification' ? profile.publicationStatus : undefined, hiringRequestStatus: hiringRequest?.status, hiringPaymentStatus: hiringRequest?.paymentStatus, hiringPaidAt: hiringRequest?.paidAt, canPublish: transaction.type === 'lawyer_verification' && transaction.status === 'paid' && isProfileComplete(profile) && !['suspended', 'deleted'].includes(profile.publicationStatus) } }) } catch (error) { return next(error) } }
export async function listMyPayments(request, response, next) { try { const filter = request.auth.user.role === 'user' ? { payerId: request.auth.user.id } : { lawyerId: request.auth.user.id }; const items = await PaymentTransaction.find(filter).sort({ createdAt: -1, _id: -1 }).select('type amountMinor currency status paidAt createdAt hiringRequestId').lean(); return response.json({ success: true, data: { items: items.map((item) => ({ id: String(item._id), type: item.type, amountMinor: item.amountMinor, currency: item.currency, status: item.status, paidAt: item.paidAt, createdAt: item.createdAt, hiringRequestId: item.hiringRequestId ? String(item.hiringRequestId) : null })) } }) } catch (error) { return next(error) } }
export async function stripeWebhook(request, response, next) { try { if (!env.STRIPE_WEBHOOK_SECRET || !env.STRIPE_SECRET_KEY) throw fail('Webhook is not configured.', 503, 'WEBHOOK_UNAVAILABLE'); const Stripe = (await import('stripe')).default; const stripe = new Stripe(env.STRIPE_SECRET_KEY); const event = stripe.webhooks.constructEvent(request.body, request.headers['stripe-signature'], env.STRIPE_WEBHOOK_SECRET); if (event.type === 'checkout.session.completed') { if (event.data.object.metadata?.type === 'hiring_fee') await fulfillHiringSession(event.data.object); else await fulfillVerificationSession(event.data.object) } if (event.type === 'checkout.session.expired') await resetExpiredCheckout(event.data.object); return response.json({ received: true }) } catch (error) { if (error.type === 'StripeSignatureVerificationError') return response.status(400).json({ success: false, error: { code: 'INVALID_WEBHOOK_SIGNATURE', message: 'Webhook signature verification failed.' } }); return next(error) } }
export async function updatePublication(request, response, next) { try { const profile = await LawyerProfile.findOne({ userId: request.auth.user.id }); if (!profile) throw fail('Professional profile was not found.', 404, 'LAWYER_PROFILE_NOT_FOUND'); if (profile.publicationStatus === 'suspended' || profile.publicationStatus === 'deleted') throw fail('This publication state cannot be changed.', 403, 'PUBLICATION_LOCKED'); const { publicationStatus } = request.body; if (publicationStatus === 'published') { if (profile.verificationStatus !== 'paid') throw fail('Verified payment is required before publishing.', 403, 'VERIFICATION_REQUIRED'); if (!isProfileComplete(profile)) throw fail('Complete your profile before publishing.', 400, 'PROFILE_INCOMPLETE'); profile.publicationStatus = 'published' } else if (profile.publicationStatus === 'published') profile.publicationStatus = 'unpublished'; else throw fail('Only a published profile can be unpublished.', 409, 'INVALID_PUBLICATION_TRANSITION'); await profile.save(); return response.json({ success: true, data: { publicationStatus: profile.publicationStatus } }) } catch (error) { return next(error) } }
