import mongoose from 'mongoose'
import { env } from '../config/env.js'
import { LawyerProfile } from '../models/LawyerProfile.js'
import { PaymentTransaction } from '../models/PaymentTransaction.js'
import { createVerificationCheckout, fulfillVerificationSession, isProfileComplete, resetExpiredCheckout } from '../services/paymentService.js'

function fail(message, statusCode, code) { return Object.assign(new Error(message), { statusCode, code }) }
export async function startVerificationCheckout(request, response, next) { try { const { transaction, checkoutUrl } = await createVerificationCheckout(request.auth.user); return response.status(201).json({ success: true, data: { transactionId: transaction.id, checkoutUrl } }) } catch (error) { return next(error) } }
export async function getPaymentStatus(request, response, next) { try { if (!mongoose.isObjectIdOrHexString(request.params.id)) throw fail('Payment was not found.', 404, 'PAYMENT_NOT_FOUND'); const transaction = await PaymentTransaction.findOne({ _id: request.params.id, payerId: request.auth.user.id, type: 'lawyer_verification' }); if (!transaction) throw fail('Payment was not found.', 404, 'PAYMENT_NOT_FOUND'); const profile = await LawyerProfile.findById(transaction.lawyerProfileId); return response.json({ success: true, data: { transactionId: transaction.id, type: transaction.type, transactionStatus: transaction.status, verificationStatus: profile.verificationStatus, publicationStatus: profile.publicationStatus, canPublish: transaction.status === 'paid' && isProfileComplete(profile) && !['suspended', 'deleted'].includes(profile.publicationStatus) } }) } catch (error) { return next(error) } }
export async function stripeWebhook(request, response, next) { try { if (!env.STRIPE_WEBHOOK_SECRET || !env.STRIPE_SECRET_KEY) throw fail('Webhook is not configured.', 503, 'WEBHOOK_UNAVAILABLE'); const Stripe = (await import('stripe')).default; const stripe = new Stripe(env.STRIPE_SECRET_KEY); const event = stripe.webhooks.constructEvent(request.body, request.headers['stripe-signature'], env.STRIPE_WEBHOOK_SECRET); if (event.type === 'checkout.session.completed') await fulfillVerificationSession(event.data.object); if (event.type === 'checkout.session.expired') await resetExpiredCheckout(event.data.object); return response.json({ received: true }) } catch (error) { if (error.type === 'StripeSignatureVerificationError') return response.status(400).json({ success: false, error: { code: 'INVALID_WEBHOOK_SIGNATURE', message: 'Webhook signature verification failed.' } }); return next(error) } }
export async function updatePublication(request, response, next) { try { const profile = await LawyerProfile.findOne({ userId: request.auth.user.id }); if (!profile) throw fail('Professional profile was not found.', 404, 'LAWYER_PROFILE_NOT_FOUND'); if (profile.publicationStatus === 'suspended' || profile.publicationStatus === 'deleted') throw fail('This publication state cannot be changed.', 403, 'PUBLICATION_LOCKED'); const { publicationStatus } = request.body; if (publicationStatus === 'published') { if (profile.verificationStatus !== 'paid') throw fail('Verified payment is required before publishing.', 403, 'VERIFICATION_REQUIRED'); if (!isProfileComplete(profile)) throw fail('Complete your profile before publishing.', 400, 'PROFILE_INCOMPLETE'); profile.publicationStatus = 'published' } else if (profile.publicationStatus === 'published') profile.publicationStatus = 'unpublished'; else throw fail('Only a published profile can be unpublished.', 409, 'INVALID_PUBLICATION_TRANSITION'); await profile.save(); return response.json({ success: true, data: { publicationStatus: profile.publicationStatus } }) } catch (error) { return next(error) } }
